SELECT
    IH.TRANSACTION_NUMBER,
    IH.SUBMISSION_DATE AS SUBMISSION_DAY,
    IH.BUYER_OBX_IDENTIFIER,
    BEJ.FILE_NAME AS BUYER_FILE_NAME,
    CB.CLIENT_NAME AS BUYER_NAME,
    E.ENTITY_NAME AS BUYER_GROUP,
    BP.BUYER_OBX AS BFP_BUYER_OBX,
    BP.BFP_PROFILE,
    BP.BFP_PROPERTIES_FILE,
    BP.BACKEND_LOCATION
FROM
    OBX.CLIENT C
    INNER JOIN OBX.INVOICE_HEADER IH ON C.OBX_IDENTIFIER = IH.SUPPLIER_OBX_IDENTIFIER
    INNER JOIN OBX.BUYER_EXTRACT_JOB BEJ ON IH.BUYER_FILE_ID = BEJ.FILE_ID
    INNER JOIN OBX.CLIENT CB ON IH.BUYER_OBX_IDENTIFIER = CB.OBX_IDENTIFIER
    INNER JOIN OBX.BUYER_EXTRACT_CONFIGURATION BEC ON IH.BUYER_OBX_IDENTIFIER = BEC.BUYER_OBX_IDENTIFIER
    INNER JOIN OBI.ACCOUNT BEAL ON BEAL.OB10_ACCOUNT_ID = IH.BUYER_OBX_IDENTIFIER
    INNER JOIN OBI.ENTITY @eudb BE ON BE.ENTITY_ID = BEAL.ENTITY_ID
    INNER JOIN OBI.ENTITY @eudb E ON E.ENTITY_ID = BE.ROOT_PARENT_ID
    LEFT JOIN BFP.BFP_PROPERTIES @uscleolink BP on BP.BUYER_OBX = IH.BUYER_OBX_IDENTIFIER
WHERE
    C.OBX_IDENTIFIER NOT IN (
        SELECT
            SUPPLIER_OBX_IDENTIFIER
        FROM
            OBX.SUPPLIER_TEST
    )
    AND IH.BUYER_OBX_IDENTIFIER NOT IN (
        SELECT
            BUYER_OBX_IDENTIFIER
        FROM
            OBX.BUYER_TEST
    )
    AND IH.SUBMISSION_DATE BETWEEN SYSDATE -1
    AND (
        SYSDATE -(((BEC.WRITE_TO_RIF_PERIOD / 60) / 1440) + 0.25)
    )
    AND IH.INVOICE_STATUS_ID = 2
    AND IH.DELETED_FLAG = 0;